-- public.tabulador definition

-- Drop table

-- DROP TABLE public.tabulador;

CREATE TABLE public.tabulador (
                                  id_estado int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
                                  estado varchar(255) NOT NULL,
                                  costo_dia numeric(12, 2) NOT NULL,
                                  CONSTRAINT tabulador_pkey PRIMARY KEY (id_estado)
);


-- public.viatico definition

-- Drop table

-- DROP TABLE public.viatico;

CREATE TABLE public.viatico (
                                id_viatico int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                fecha_inicio date NOT NULL,
                                fecha_cambio date NOT NULL,
                                uuid_viatico uuid NOT NULL,
                                monto numeric NOT NULL,
                                CONSTRAINT viatico_pk PRIMARY KEY (id_viatico)
);


-- public.gasto definition

-- Drop table

-- DROP TABLE public.gasto;

CREATE TABLE public.gasto (
                              id_gasto int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              monto numeric NOT NULL,
                              fecha_inicio date NOT NULL,
                              fecha_cambio date NOT NULL,
                              uuid_gasto uuid NOT NULL,
                              id_viatico int4 NOT NULL,
                              CONSTRAINT gasto_pk PRIMARY KEY (id_gasto),
                              CONSTRAINT gasto_fk FOREIGN KEY (id_viatico) REFERENCES public.viatico(id_viatico)
);